server:
  port: 9999
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/en-hui/SpringCloud-Config-Center.git
      label: master
  application:
    name: Config-Center
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #无密码形式
      #defaultZone: http://localhost:7001/eureka/
      #安全验证，有密码模式
      defaultZone: http://admin:admin@localhost:7001/eureka/
